TRAINING:
  INPUT_SIZE: 128
  LR: 5.0e-05
  LR_DROP: 20
  BATCH_SIZE: 1
  WEIGHT_DECAY: 0.0001
  EPOCHS: 50
  CLIP_MAX_NORM: 0.1
  EVAL_INTERVAL: 1
  SAVE_CKPT_INTERVAL: 1
  SAVE_BEST_CKPT_CRITERION: f1
  RESUME: ''
  START_EPOCH: 1
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  USE_CLS_TOKEN: true
  LOSS:
    TYPE: bce
    FOCAL_PARAMS:
      ALPHA: 0.8
      GAMMA: 2
    LOCALIZATION_LOSS:
      USE: true
      TYPE: kl
      SPATIAL_FEAT_SRC: fusion
      FUSION_BETA: 0.9
      SPATIAL_FEAT_INTERPOLATION: bilinear
      FEAT_CHANNEL_REDUCTION: squeeze_mean
      GT_SEG_PROCESS_METHOD: gauss
      GT_SEG_PROCESS_KERNEL_SIZE: 51
      ALPHA: 1000
      PATIENT_LIST: null
    SAMPLING_LOSS:
      USE: false
      POS_NEG_RATIO: 1
      FULL_NEG_SCAN_RATIO: 0.5
MODEL:
  PRETRAINED_WEIGHTS: null
  NUM_CLASSES: 2
  PATCH_SIZE: 16
  POSITION_EMBEDDING:
    TYPE: sine
    Z_SIZE: 40
    FIT_MODE: interpolate
  PATCH_EMBED:
    NAME: patch_embed
    RETURN_INTERM_LAYERS: true
    DILATION: false
  TRANSFORMER:
    TYPE: vit
    NUM_LAYERS: 12
    FORWARD_EXPANSION_RATIO: 4
    EMBED_SIZE: 768
    HEADS: 12
    DROP_PATH: 0.1
    FORWARD_DROP_P: 0.1
    USE_CLS_TOKEN: false
    ATTENTION_3D: false
DATA:
  DATASET_DIR: /mnt/DATA1/Sagi/Data/
  DATASETS: isles2022
  DATA_SPLIT_FILE: datasets/data_splits/isles22/train_val_test_split.json
  DATA_FOLD: 0
  MODALITIES: all
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/
  PREPROCESS:
    RESIZE_MODE: interpolate
    MASK_PROSTATE: true
    CROP_PROSTATE: true
    CROP_PADDING: 0
TEST:
  DATASET_PATH: null
  BATCH_SIZE: 1
  CLIP_MAX_NORM: 0.1
  CHECKPOINT: best
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/
DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
