DATA:
  DATASET_DIR: /mnt/DATA1/Sagi/Data/
  DATASETS: BraTS2020
  DATA_SPLIT_FILE: datasets/data_splits/brats20/train_val_test_split.json
  PREPROCESS:
    RESIZE_MODE: 'interpolate'  # options: interpolate or padding
    SCAN_NORM_MODE: 'slice'  # options: 'slice', 'scan'

TRAINING:
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/
  INPUT_SIZE: 256
  LR: 0.00001
  SCAN_SEG_SIZE: 32
  BATCH_SIZE: 32
  MAX_SCAN_SIZE: null
  WEIGHT_DECAY: 0.0001
  EPOCHS: 25
  CLIP_MAX_NORM: 0
  EVAL_INTERVAL: 1
  SAVE_CKPT_INTERVAL: 1
  SAVE_BEST_CKPT_CRITERION: 'f1'
  RESUME: ''
  START_EPOCH: 1
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  LOSS:
    TYPE: 'bce' # options: 'bce', 'focal'
    LOCALIZATION_LOSS:
      USE: true
      TYPE: 'kl' # options: 'kl', 'mse', 'mse_fgbg', ('kl_fgbg') gradmask
      SPATIAL_FEAT_SRC: 'fusion'  # options: 'attn', 'bb_feat', 'fusion', fusion_experimental
      ATTENTION_METHOD: 'raw_attn' # options: 'gradcam', 'relevance_map', 'lrp', 'rollout', 'beyond_attn' gradcam
      FUSION_BETA: 0.85
      SPATIAL_FEAT_INTERPOLATION: 'bilinear' # options: 'bilinear', 'nearest'
      FEAT_CHANNEL_REDUCTION: 'squeeze_mean' # options: 'squeeze_mean', 'select_max', 'squeeze_max', 'learned'
      SPATIAL_MAP_NORM: 'softmax'
      GT_SEG_PROCESS_METHOD: 'gauss' # options: 'None', 'gauss', 'learned_S1', 'learned_S2', 'learned_D1', 'learned_D2', 'learned_d1'
      GT_SEG_PROCESS_KERNEL_SIZE:  51  # gaussian smoothing kernel size on the gt segmentation
      ALPHA: 1000
      PATIENT_LIST: null

MODEL:
  PRETRAINED_WEIGHTS:
  NUM_CLASSES: 2
  PATCH_SIZE: 16
  POSITION_EMBEDDING:
    TYPE: sine # sine, learned, null
  VIT_ENCODER:
    NUM_LAYERS: 12
    FORWARD_EXPANSION_RATIO: 4
    EMBED_SIZE: 768
    HEADS: 12
    DROP_PATH: 0.1
    FORWARD_DROP_P: 0.1
    USE_CLS_TOKEN: true
    ATTENTION_3D: false

TEST:
  CHECKPOINT: 'best'
  CHECKPOINT_PARENT_DIR: null
  CLS_THRESH: 0.5
  NUM_WORKERS: 4

DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
