TRAINING:
  INPUT_SIZE: 256
  LR: 1.0e-05
  LR_DROP: 20
  SCAN_SEG_SIZE: 32
  BATCH_SIZE: 32
  LAST_BATCH_MIN_RATIO: 0
  MAX_SCAN_SIZE: null
  WEIGHT_DECAY: 0.0001
  EPOCHS: 25
  CLIP_MAX_NORM: 0
  EVAL_INTERVAL: 1
  SAVE_CKPT_INTERVAL: 1
  SAVE_BEST_CKPT_CRITERION: f1
  RESUME: ''
  START_EPOCH: 1
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  LOSS:
    TYPE: bce
    LOCALIZATION_LOSS:
      USE: true
      TYPE: mse_fgbg
      SPATIAL_FEAT_SRC: attn
      ATTENTION_METHOD: relevance_map
      FUSION_BETA: 0.95
      SPATIAL_FEAT_INTERPOLATION: bilinear
      FEAT_CHANNEL_REDUCTION: squeeze_mean
      SPATIAL_MAP_NORM: softmax
      GT_SEG_PROCESS_METHOD: gauss
      GT_SEG_PROCESS_KERNEL_SIZE: 0
      ALPHA: 0.1
      PATIENT_LIST: null
MODEL:
  PRETRAINED_WEIGHTS: null
  NUM_CLASSES: 2
  PATCH_SIZE: 16
  POSITION_EMBEDDING:
    TYPE: sine
    Z_SIZE: 40
    FIT_MODE: interpolate
  VIT_ENCODER:
    NUM_LAYERS: 12
    FORWARD_EXPANSION_RATIO: 4
    EMBED_SIZE: 768
    HEADS: 12
    DROP_PATH: 0.1
    FORWARD_DROP_P: 0.1
    USE_CLS_TOKEN: true
    ATTENTION_3D: false
DATA:
  DATASET_DIR: /mnt/DATA1/Sagi/Data/
  DATASETS: BraTS2020
  ANNOT_TYPE: null
  DATA_SPLIT_FILE: datasets/data_splits/brats20/train_val_test_split.json
  DATA_FOLD: 0
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/
  PREPROCESS:
    RESIZE_MODE: interpolate
    GLAND_SEG_DIR: null
    MASK_ORGAN: true
    CROP_ORGAN_SLICES: true
    CROP_ORGAN_SPATIAL: true
    SCAN_NORM_MODE: slice
    CROP_PADDING: 0
TEST:
  DATASET_PATH: null
  BATCH_SIZE: 1
  CLIP_MAX_NORM: 0
  CHECKPOINT: best
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/
DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
