TRAINING:
  INPUT_SIZE: 128
  LR: 0.00001
  LR_DROP: 20
  BATCH_SIZE: 1
  WEIGHT_DECAY: 0.0001
  EPOCHS: 50
  CLIP_MAX_NORM: 0.1
  EVAL_INTERVAL: 1
  SAVE_CKPT_INTERVAL: 1
  SAVE_BEST_CKPT_CRITERION: 'f1'
  RESUME: ''
  START_EPOCH: 1
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  USE_CLS_TOKEN: true
  LOSS:
    TYPE: 'bce' # options: 'bce', 'focal'
    FOCAL_PARAMS:
      ALPHA: 0.8
      GAMMA: 2
    LOCALIZATION_LOSS:
      USE: false
      TYPE: 'kl' # options: 'kl', 'mse', 'mse_fgbg', ('kl_fgbg')
      SPATIAL_FEAT_SRC: 'fusion'  # options: 'attn', 'bb_feat', 'fusion',
      ATTENTION_METHOD: 'raw_attn' # options: 'raw_attn', 'relevance_map', 'lrp', 'rollout', 'beyond_attn'
      FUSION_BETA: 'learned'
      SPATIAL_FEAT_INTERPOLATION: 'bilinear' # options: 'bilinear', 'nearest'
      FEAT_CHANNEL_REDUCTION: 'squeeze_mean' # options: 'squeeze_mean', 'select_max', 'squeeze_max'
      GT_SEG_PROCESS_METHOD: 'gauss' # options: 'None', 'gauss', 'learned_S1', 'learned_S2', 'learned_D1', 'learned_D2', 'learned_d1'
      GT_SEG_PROCESS_KERNEL_SIZE: 51  # gaussian smoothing kernel size on the gt segmentation
      ALPHA: 100
      PATIENT_LIST: null
    SAMPLING_LOSS:
      USE: false
      POS_NEG_RATIO: 1
      FULL_NEG_SCAN_RATIO: 0.5

MODEL:
  PRETRAINED_WEIGHTS:
  NUM_CLASSES: 2
  PATCH_SIZE: 16
  POSITION_EMBEDDING:
    TYPE: sine # sine, learned, null
    Z_SIZE: 40
    FIT_MODE: interpolate # interpolate, prune
  PATCH_EMBED:
    NAME: patch_embed # convnext  resnet101 , patch_embed
    RETURN_INTERM_LAYERS: true
    DILATION: false
  TRANSFORMER:
    TYPE: vit # vit, max_vit
    NUM_LAYERS: 12
    FORWARD_EXPANSION_RATIO: 4
    EMBED_SIZE: 768
    HEADS: 12
    DROP_PATH: 0.1
    FORWARD_DROP_P: 0.1
    USE_CLS_TOKEN: false
    ATTENTION_3D: false

DATA:
  DATASET_DIR: /mnt/DATA1/Sagi/Data/
  DATASETS: Prostate_MRI/PICAI/nnUNet_raw_data/Task2201_picai_baseline/
  DATA_SPLIT_FILE: datasets/data_splits/picai22/train_val_test_split.json
  DATA_FOLD: 0
  PREPROCESS:
    RESIZE_MODE: interpolate  # options: interpolate or padding
    GLAND_SEG_DIR: '/mnt/DATA1/Sagi/Data/Prostate_MRI/PICAI/annotations/picai_labels/anatomical_delineations/whole_gland/AI/Bosma22b_resmapled/'
    MASK_PROSTATE: true # apply prostate mask on scan
    CROP_PROSTATE: true # crop scan according to prostate mask
    CROP_PADDING: 0 # padding around prostate crop (0 for minimal cropping)
  MODALITIES: all # 'all' for all available modalities. For specific modalities in a list of the desired ones (example: [])
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/

TEST:
  DATASET_PATH:
  BATCH_SIZE: 1
  CLIP_MAX_NORM: 0.1
  CHECKPOINT: 'best'
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/

DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
