DATA:
  DATASET_DIR: /media/rotem/ab5c6608-2520-4a40-bc1e-c55b146472a2/Sagi/Data/  # Full path to dataset parent directory
  DATASETS: LiTS17 # Name of dataset directory
  DATA_SPLIT_FILE: datasets/data_splits/lits17/train_val_test_split.json # Path to dataset split file. Files located at: datasets/data_splits
  ANNOT_TYPE: 'organ'   # Annotation type to use if there is more than one (for LiTS17 options are: 'lesion', 'organ')
  PREPROCESS:
    RESIZE_MODE: interpolate    # Options: 'interpolate' or 'padding'. Resize method
    MASK_ORGAN: false   # Apply organ mask on scan
    CROP_ORGAN_SLICES: false    # Crop scan in the slices dimension according to organ mask
    CROP_ORGAN_SPATIAL: false   # Crop scan in the spatial dimensions according to organ mask
    CROP_PADDING: 0   # Padding around organ crop (0 for minimal cropping)
    SCAN_NORM_MODE: 'slice'   # Options: 'slice', 'scan', None. Minmax normalization option (for 'slice' normalization is applied separately for each slice, for 'scan' it is applied on the entire scan at once)

TRAINING:
  OUTPUT_DIR: /media/rotem/ab5c6608-2520-4a40-bc1e-c55b146472a2/Sagi/Models/LGMViT/  # Path to parent directory where the experiments (checkpoints) will be saved to
  INPUT_SIZE: 256   # Spatial input size (H and W)
  LR: 0.00001   # Initial learning rate
  SCAN_SEG_SIZE: 32   # Number of slices for each forward pass. This number must be a factor of the batch size. Reduce this number in cases where the desired batch size exceeds the GPU memory.
  BATCH_SIZE: 32    # Effective batch size
  LAST_BATCH_MIN_RATIO: 0.7   # Value between 0 and 1 (0 represents no size limit). The minimum size of the last batch (set by the ratio with the batch size) of a scan that is acceptable. Scans where the last batch is smaller than this number will be trimmed at the edges of the scan.
  WEIGHT_DECAY: 0.0001    # Weight decay parameter
  EPOCHS: 25    # Number of epochs to train
  CLIP_MAX_NORM: 0    # Clip gradients
  EVAL_INTERVAL: 1    # Interval length (in epochs) for evaluation on validation set
  SAVE_CKPT_INTERVAL: 5   # Interval length (in epochs) to save checkpoints
  SAVE_BEST_CKPT_CRITERION: 'f1'    # Options: 'f1', 'acc', 'auroc', 'auprc', 'cohen_kappa'. Criterion in which to save checkpoint for best epoch.
  RESUME: ''    # Resume from checkpoint. Options: 'latest' (resumes from the last saved epoch), insert full path to checkpoint, insert url to checkpoint
  START_EPOCH: 1    # Initialize the epoch count of training session
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5   # Binary classification threshold for evaluation of the model's prediction
  LOSS:
    TYPE: 'bce' # Classification loss type (currently only supports binary cross entropy)
    LOCALIZATION_LOSS:
      USE: true   # Apply localization loss
      TYPE: 'kl'    # Localization loss type. Options: 'kl', 'mse', 'l1', 'mse_fgbg'(RobustViT)
      SPATIAL_FEAT_SRC: 'fusion'    # Options: 'attn', 'bb_feat', 'fusion'. Source for attribution map for localization supervision
      ATTENTION_METHOD: 'last_layer_attn'    # Options: 'last_layer_attn', 'rollout', 'relevance_map'(GAE). Attention method to use for attention-based map
      FUSION_BETA: 0.95   # Value between 0 and 1. Weighting parameter of the EAFEM
      SPATIAL_FEAT_INTERPOLATION: 'bilinear'    # Options:  'bilinear', 'nearest'. Interpolation method to resize attribution maps
      FEAT_CHANNEL_REDUCTION: 'squeeze_mean'    # Optiions: 'squeeze_mean', 'select_max', 'squeeze_max'. Channel reduction methods in attribution map generation process (heads/embedding reduction)
      SPATIAL_MAP_NORM: 'softmax'   # Options: 'softmax', 'minmax'. Attribution maps normalization methods in localization loss
      GT_SEG_PROCESS_METHOD: 'gauss'    # Options: 'None', 'gauss'. GT process method
      GT_SEG_PROCESS_KERNEL_SIZE: 51    # Kernel size for GT process (for gauss)
      ALPHA: 250   # Weighting parameter of the localization loss
      PATIENT_LIST: datasets/LGS_patient_lists/lits17/lits17_patient_list_60.json    # Path to file of the list of cases to apply localization loss on (for ablation). Default (None) uses all available cases. Files located at: datasets/LGS_patient_lists

MODEL:
  PRETRAINED_WEIGHTS:   # Path to pretrained weights
  NUM_CLASSES: 2    # Number of classes for classification (currently only supports 2 - binary classification)
  PATCH_SIZE: 16    # Patch size for patch embedding module
  POSITION_EMBEDDING:
    TYPE: sine    # Options: 'sine', 'learned', null. Type of positional encoding
  VIT_ENCODER:
    NUM_LAYERS: 12    # Number of ViT encoder blocks
    FORWARD_EXPANSION_RATIO: 4    # MLP expansion parameter in ViT block
    EMBED_SIZE: 768   # Embedding size
    HEADS: 12   # Number of heads
    DROP_PATH: 0.1    # Drop path ratio (ViT Block)
    FORWARD_DROP_P: 0.1   # Drop path ratio (MLP inside the ViT Block)
    USE_CLS_TOKEN: true   # Use class token (currently mandatory)

DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
