TRAINING:
  LR: 0.00001
  LR_DROP: 12
  BATCH_SIZE: 1
  WEIGHT_DECAY: 0.0001
  EPOCHS: 50
  CLIP_MAX_NORM: 0.1
  EVAL_INTERVAL: 1
  RESUME: ''
  START_EPOCH: 0
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5

MODEL:
  PRETRAINED_WEIGHTS: /mnt/DATA2/Sagi/Models/ProLesClassifier/proles_picai_input128_resnet101_pos_emb_sine_t_depth_6_emb_size_2048_mask_crop_prostate_sheba_only/ckpt/checkpoint0048.pth
  NUM_CLASSES: 2
  POSITION_EMBEDDING:
    TYPE: sine
    Z_SIZE: 40
    MODE: interpolate
  BACKBONE:
    NAME: resnet101
    RETURN_INTERM_LAYERS: false
    DILATION: false
  TRANSFORMER:
    NUM_LAYERS: 6
    FORWARD_EXPANSION_RATIO: 4
    EMBED_SIZE: 2048
    HEADS: 8
    DROP_PATH: 0.1
    FORWARD_DROP_P: 0.1

DATA:
  DATASET_DIR: /mnt/DATA2/Sagi/Data/ # proles2021_debug   picai2022
  DATASETS: PICAI/processed_data/processed_data_t2w_bias_corr_resgist_t2w_hist_stnd_normalized/
  DATA_LIST: # /mnt/DATA2/Sagi/Data/PICAI/processed_data/processed_data_t2w_bias_corr_resgist_t2w_hist_stnd_normalized/fold_0/data_list.json
  DATA_FOLD: 0
  INPUT_SIZE: 128
  PREPROCESS:
    RESIZE_MODE: interpolate  # options: interpolate or padding
    MASK_PROSTATE: true # apply prostate mask on scan
    CROP_PROSTATE: true # crop scan according to prostate mask
    CROP_PADDING: 0 # padding around prostate crop (0 for minimal cropping)
  MODALITIES: all # 'all' for all available modalities. For specific modalities in a list of the desired ones (example: [])
  OUTPUT_DIR: /mnt/DATA2/Sagi/Models/ProLesClassifier/

TEST:
  DATASET_PATH: /mnt/DATA2/Sagi/Data/PICAI/processed_data/processed_data_t2w_bias_corr_resgist_t2w_hist_stnd_normalized/fold_0/val/
  BATCH_SIZE: 1
  CLIP_MAX_NORM: 0.1
  CHECKPOINT: 34
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  OUTPUT_DIR: /mnt/DATA2/Sagi/Models/ProLesClassifier/

DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
