TRAINING:
  LR: 0.00001
  LR_DROP: 12
  BATCH_SIZE: 1
  WEIGHT_DECAY: 0.0001
  EPOCHS: 300
  CLIP_MAX_NORM: 0.1
  EVAL_INTERVAL: 1
  RESUME: ''
  START_EPOCH: 0
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  SAMPLING_LOSS:
    USE: true
    POS_NEG_RATIO: 1.0
    FULL_NEG_SCAN_RATIO: 0.5

MODEL:
  PRETRAINED_WEIGHTS:
  NUM_CLASSES: 2
  PATCH_SIZE: 8
  POSITION_EMBEDDING:
    TYPE: sine # sine, learned
    Z_SIZE: 40
    FIT_MODE: interpolate # interpolate, prune
  BACKBONE:
    NAME: resnet101
    RETURN_INTERM_LAYERS: false
    DILATION: false
  TRANSFORMER:
    TYPE: vit # vit, max_vit
    NUM_LAYERS: 6
    FORWARD_EXPANSION_RATIO: 4
    EMBED_SIZE: 512
    HEADS: 8
    DROP_PATH: 0.1
    FORWARD_DROP_P: 0.1
    ATTENTION_3D: true

DATA:
  DATASET_DIR: /mnt/DATA2/Sagi/Data/
  DATASETS: PICAI/processed_data/processed_data_t2w_bias_corr_resgist_t2w_hist_stnd_normalized/
  DATA_LIST: # /mnt/DATA2/Sagi/Data/PICAI/processed_data/processed_data_t2w_bias_corr_resgist_t2w_hist_stnd_normalized/fold_0/data_list.json
  DATA_FOLD: 0
  INPUT_SIZE: 128
  PREPROCESS:
    RESIZE_MODE: interpolate  # options: interpolate or padding
    MASK_PROSTATE: true # apply prostate mask on scan
    CROP_PROSTATE: true # crop scan according to prostate mask
    CROP_PADDING: 0 # padding around prostate crop (0 for minimal cropping)
  MODALITIES: all # 'all' for all available modalities. For specific modalities in a list of the desired ones (example: [])
  OUTPUT_DIR: /mnt/DATA2/Sagi/Models/ProLesClassifier/

TEST:
  DATASET_PATH: /mnt/DATA2/Sagi/Data/PICAI/processed_data/processed_data_t2w_bias_corr_resgist_t2w_hist_stnd_normalized/fold_0/val/
  BATCH_SIZE: 1
  CLIP_MAX_NORM: 0.1
  CHECKPOINT: 34
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  OUTPUT_DIR: /mnt/DATA2/Sagi/Models/ProLesClassifier/

DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
