TRAINING:
  LR: 0.00001
  LR_DROP: 12
  BATCH_SIZE: 1
  WEIGHT_DECAY: 0.0001
  EPOCHS: 50
  CLIP_MAX_NORM: 0.1
  EVAL_INTERVAL: 1
  SAVE_CKPT_INTERVAL: 1
  SAVE_BEST_CKPT_CRITERION: 'f1'
  RESUME: ''
  START_EPOCH: 1
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  LOSS:
    TYPE: 'bce' # options: 'bce', 'focal'
    FOCAL_PARAMS:
      ALPHA: 0.8
      GAMMA: 2
    LOCALIZATION_LOSS:
      USE: false
      TYPE: 'kl' # options: 'kl
      ALPHA: 10
      PATIENT_LIST: null
    SAMPLING_LOSS:
      USE: true
      POS_NEG_RATIO: 1
      FULL_NEG_SCAN_RATIO: 0.5

MODEL:
  PRETRAINED_WEIGHTS:
  NUM_CLASSES: 2
  PATCH_SIZE: 32
  POSITION_EMBEDDING:
    TYPE: sine # sine, learned, null
    Z_SIZE: 40
    FIT_MODE: interpolate # interpolate, prune
  PATCH_EMBED:
    NAME: resnet101 # convnext  resnet101 , patch_embed
    RETURN_INTERM_LAYERS: true
    DILATION: false
  TRANSFORMER:
    TYPE: vit # vit, max_vit
    NUM_LAYERS: 6
    FORWARD_EXPANSION_RATIO: 4
    EMBED_SIZE: 2048
    HEADS: 8
    DROP_PATH: 0.1
    FORWARD_DROP_P: 0.1
    ATTENTION_3D: true

DATA:
  DATASET_DIR: /mnt/DATA1/Sagi/Data/Prostate_MRI/processed_data/
  DATASETS: picai/processed_data_t2w_bias_corr_resgist_t2w_hist_stnd_normalized/
  DATA_SPLIT_FILE: '/mnt/DATA1/Sagi/Data/Prostate_MRI/processed_data/picai/train_val_splits_debug.json'
  DATA_FOLD: 0
  INPUT_SIZE: 128
  PREPROCESS:
    RESIZE_MODE: interpolate  # options: interpolate or padding
    MASK_PROSTATE: true # apply prostate mask on scan
    CROP_PROSTATE: true # crop scan according to prostate mask
    CROP_PADDING: 0 # padding around prostate crop (0 for minimal cropping)
  MODALITIES: all # 'all' for all available modalities. For specific modalities in a list of the desired ones (example: [])
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGLViT/

TEST:
  DATASET_PATH: /mnt/DATA1/Sagi/Data/Prostate_MRI/processed_data/picai/processed_data_t2w_bias_corr_resgist_t2w_hist_stnd_normalized/fold_0/val/
  BATCH_SIZE: 1
  CLIP_MAX_NORM: 0.1
  CHECKPOINT: 6
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGLViT/

DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
