TRAINING:
  INPUT_SIZE: 256
  LR: 0.00001
  LR_DROP: 20
  SCAN_SEG_SIZE: 16
  BATCH_SIZE: 16
  WEIGHT_DECAY: 0.0001
  EPOCHS: 5
  CLIP_MAX_NORM: 0
  EVAL_INTERVAL: 1
  SAVE_CKPT_INTERVAL: 1
  SAVE_BEST_CKPT_CRITERION: 'f1'
  RESUME: ''
  START_EPOCH: 1
  EVAL: false
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  LOSS:
    TYPE: 'bce' # options: 'bce'
    LOCALIZATION_LOSS:
      USE: true
      TYPE: 'res' # options: 'kl', 'mse', 'mse_fgbg', ('kl_fgbg') gradmask
      SPATIAL_FEAT_SRC: 'attn'  # options: 'attn', 'bb_feat', 'fusion', fusion_experimental
      ATTENTION_METHOD: 'relevance_map' # options: 'gradcam', 'relevance_map', 'lrp', 'rollout', 'beyond_attn' gradcam
      FUSION_BETA: 0.95
      SPATIAL_FEAT_INTERPOLATION: 'bilinear' # options: 'bilinear', 'nearest'
      FEAT_CHANNEL_REDUCTION: 'squeeze_mean' # options: 'squeeze_mean', 'select_max', 'squeeze_max', 'learned'
      SPATIAL_MAP_NORM: 'softmax'
      GT_SEG_PROCESS_METHOD: 'learned_D2' # options: 'None', 'gauss', 'learned_S1', 'learned_S2', 'learned_D1', 'learned_D2', 'learned_d1'
      GT_SEG_PROCESS_KERNEL_SIZE:  51  # gaussian smoothing kernel size on the gt segmentation
      ALPHA: 100
      PATIENT_LIST: null

MODEL:
  PRETRAINED_WEIGHTS:
  NUM_CLASSES: 2
  PATCH_SIZE: 16
  POSITION_EMBEDDING:
    TYPE: sine # sine, learned, null
    Z_SIZE: 40
    FIT_MODE: interpolate # interpolate, prune
  VIT_ENCODER: 
    NUM_LAYERS: 12
    FORWARD_EXPANSION_RATIO: 4
    EMBED_SIZE: 768
    HEADS: 12
    DROP_PATH: 0.1
    FORWARD_DROP_P: 0.1
    USE_CLS_TOKEN: true
    ATTENTION_3D: false

DATA:
  DATASET_DIR: /mnt/DATA1/Sagi/Data/
  DATASETS: BraTS2020
  DATA_SPLIT_FILE: datasets/data_splits/brats20/train_val_split_debug.json
  DATA_FOLD: 0
  PREPROCESS:
    RESIZE_MODE: interpolate  # options: interpolate or padding
    SCAN_NORM_MODE: 'scan'  # options: 'slice', 'scan'
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/

TEST:
  DATASET_PATH:
  BATCH_SIZE: 1
  CLIP_MAX_NORM: 0
  CHECKPOINT: 'best'
  NUM_WORKERS: 4
  CLS_THRESH: 0.5
  OUTPUT_DIR: /mnt/DATA1/Sagi/Models/LGMViT/

DISTRIBUTED:
  WORLD_SIZE: 1
  DIST_URL: env://
